### ISSUE TITLE
OCIArtifactPullFailed GitLab Malformatted String - scope=repository%!A(MISSING)mygroup%!F(MISSING)d2-infra%!F(MISSING)

### ISSUE THREAD

**Issue by Aubermean** [controlplaneio-fluxcd/d2-fleet#7]
Hi Stefan,

Trying to get D2 working with GitLab (as I easily managed with D1) for a homelab setup, but running into this issue:

`failed to determine artifact digest: GET https://gitlab.com/jwt/auth?scope=repository%!A(MISSING)mygroup%!F(MISSING)d2-infra%!F(MISSING)monitoring%!A(MISSING)pull&service=container_registry: DENIED: access forbidden`

Looks like some Golang string formatting error? I've obviously done all to make sure its not an auth or PAT scope issue...

`infra.yaml`

```
    - apiVersion: source.toolkit.fluxcd.io/v1beta2
      kind: OCIRepository
      metadata:
        name: infra
        namespace: << inputs.tenant >>
      spec:
        interval: 5m
        serviceAccountName: flux
        url: "oci://registry.gitlab.com/mygroup/d2-infra/<< inputs.tenant >>"
        ref:
          tag: << inputs.tag >>
```

It works fine in `flux-instance.yaml`:

```
  sync:
    kind: OCIRepository
    url: "oci://registry.gitlab.com/mygroup/d2-fleet"
    ref: "latest"
    path: "clusters/staging"
    pullSecret: "gitlab-auth"
```

Sorry if I am missing something obvious. I've been trying to figure it out on my own for 3 hours :)

**Comment by stefanprodan** [comment]
In the ResourceSets have you've update the secret name everywhere? To find out do a quick search for `ghcr-auth` and `gitlab-auth`.

**Comment by Aubermean** [comment]
from `infra.yaml`
```
  resources:
    - apiVersion: v1
      kind: Namespace
      metadata:
        name: << inputs.tenant >>
    - apiVersion: v1
      kind: ConfigMap
      metadata:
        name: flux-runtime-info
        namespace: << inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/flux-runtime-info"
    - apiVersion: v1
      kind: Secret
      metadata:
        name: ghcr-auth
        namespace: << inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/ghcr-auth"
    - apiVersion: v1
      kind: Secret
      metadata:
        name: gitlab-auth
        namespace: << inputs.tenant >>
        annotations:
          fluxcd.controlplane.io/copyFrom: "flux-system/gitlab-auth"
    - apiVersion: v1
      kind: ServiceAccount
      metadata:
        name: flux
        namespace: << inputs.tenant >>
      imagePullSecrets:
        - name: ghcr-auth
        - name: gitlab-auth
```


I believe I have, I have left the other ghcr-auth secret in place for the operator and other things still on Github.

What has me confused is the Golang `%!F(MISSING)` type errors, the reason I have access forbidden is that the URL/path is malformatted, if the secret was wrong or missing it gives a different error (denied instead of forbidden).

Thanks for the fast reply :)
